"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](#DFCCFB)\
$os\
[](bg:#BEADFA fg:#DFCCFB)\
$username\
[](bg:#A5DD9B fg:#BEADFA)\
$directory\
[](fg:#A5DD9B bg:#D2E0FB)\
$git_branch\
$git_status\
[](fg:#D2E0FB bg:#FFC0D9)\
$python\
$nodejs\
$swift\
$rust\
$golang\
$php\
$ruby\
$julia\
[](fg:#FFC0D9 bg:#FFE9AE)\
$time\
$battery\
[](fg:#FFE9AE)\
$line_break$character"""

[os]
disabled = false
style = "bg:#DFCCFB fg:#256c8c"

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[username]
show_always = true
style_user = "fg:#256c8c bg:#BEADFA"
style_root = "fg:#256c8c bg:#BEADFA"
format = '[ $user ]($style)'

[directory]
style = "fg:#256c8c bg:#A5DD9B"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#E0AED0"
format = '[[ $symbol $branch ](fg:#256c8c bg:#D2E0FB)]($style)'

[git_status]
style = "bg:#E0AED0"
format = '[[($all_status$ahead_behind )](fg:#256c8c bg:#D2E0FB)]($style)'

[python]
symbol = " "
style = "bg:#AC87C5"
format = '[[ $symbol ($version) ](fg:#256c8c bg:#FFC0D9)]($style)'

[nodejs]
symbol = ""
style = "bg:#AC87C5"
format = '[[ $symbol ($version) ](fg:#256c8c bg:#AC87C5)]($style)'

[rust]
symbol = ""
style = "bg:#AC87C5"
format = '[[ $symbol ($version) ](fg:#256c8c bg:#AC87C5)]($style)'

[golang]
symbol = ""
style = "bg:#AC87C5"
format = '[[ $symbol ($version) ](fg:#256c8c bg:#AC87C5)]($style)'

[php]
symbol = ""
style = "bg:#AC87C5"
format = '[[ $symbol ($version) ](fg:#256c8c bg:#AC87C5)]($style)'

[ruby]
symbol = " "
style = "bg:#AC87C5"
format = '[[ $symbol ($version) ](fg:#256c8c bg:#AC87C5)]($style)'

[julia]
symbol = ""
style = "bg:#AC87C5"
format = '[[ $symbol ($version) ](fg:#256c8c bg:#AC87C5)]($style)'

[java]
symbol = " "
style = "bg:#AC87C5"
format = '[[ $symbol ($version) ](fg:#256c8c bg:#AC87C5)]($style)'

[swift]
symbol = " "
style = "bg:#AC87C5"
format = '[[ $symbol ($version) ](fg:#256c8c bg:#AC87C5)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[✧˚·. $time ✧˚·.](fg:#256c8c bg:#FFE9AE)]($style)'

[battery]
disabled = false
full_symbol = '󰁹'
charging_symbol = '󰂄 '
discharging_symbol = '󰂃'
empty_symbol = '󰂎'
format = '[$symbol$percentage]($style)'

[[battery.display]]
threshold = 10
style = 'fg:#ff0038 bg:#FFE9AE'

[[battery.display]]
threshold = 30
style = "fg:#FFB000 bg:#FFE9AE"

[[battery.display]]
threshold = 100
style = "fg:#9ADE7B bg:#FFE9AE"

[line_break]
disabled = false

[character]
disabled = false
success_symbol = "[❯](#6ccf95)"
error_symbol = '[❯](#fe6156)'
vimcmd_symbol = '[](#6ccf95)'
